#!/usr/bin/env node

/**
 * Deployment Artifact Recorder
 * 
 * This script updates DEPLOYMENT_LINKS.md with the latest deployment information
 * after a successful IC mainnet deployment.
 * 
 * Usage:
 *   node scripts/recordDeploymentArtifact.js --frontend <frontend-id> --backend <backend-id>
 * 
 * Or with environment variables:
 *   FRONTEND_CANISTER_ID=xyz BACKEND_CANISTER_ID=abc node scripts/recordDeploymentArtifact.js
 * 
 * Automated mode (resolves IDs from dfx):
 *   node scripts/recordDeploymentArtifact.js --auto
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// Parse command line arguments
function parseArgs() {
  const args = process.argv.slice(2);
  const result = {};
  
  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    if (arg === '--auto') {
      result.auto = true;
    } else if (arg.startsWith('--')) {
      const key = arg.replace(/^--/, '');
      const value = args[i + 1];
      result[key] = value;
      i++; // Skip next arg since we used it as value
    }
  }
  
  return result;
}

// Get canister ID from dfx
function getCanisterIdFromDfx(canisterName) {
  try {
    const output = execSync(`dfx canister id ${canisterName} --network ic`, {
      encoding: 'utf8',
      stdio: 'pipe'
    });
    return output.trim();
  } catch (error) {
    return null;
  }
}

// Get canister IDs from args, environment, or dfx
function getCanisterIds() {
  const args = parseArgs();
  
  let frontendId = args.frontend || process.env.FRONTEND_CANISTER_ID;
  let backendId = args.backend || process.env.BACKEND_CANISTER_ID;
  
  // If auto mode or IDs not provided, try to resolve from dfx
  if (args.auto || !frontendId || !backendId) {
    console.log('🔍 Attempting to resolve canister IDs from dfx...\n');
    
    if (!frontendId) {
      frontendId = getCanisterIdFromDfx('frontend');
      if (frontendId) {
        console.log('   ✅ Frontend ID resolved:', frontendId);
      }
    }
    
    if (!backendId) {
      backendId = getCanisterIdFromDfx('backend');
      if (backendId) {
        console.log('   ✅ Backend ID resolved:', backendId);
      }
    }
    
    console.log('');
  }
  
  if (!frontendId || !backendId) {
    console.error('❌ Error: Missing canister IDs');
    console.error('');
    console.error('Could not resolve canister IDs automatically.');
    console.error('');
    console.error('Usage:');
    console.error('  node scripts/recordDeploymentArtifact.js --frontend <id> --backend <id>');
    console.error('');
    console.error('Or set environment variables:');
    console.error('  FRONTEND_CANISTER_ID=<id> BACKEND_CANISTER_ID=<id> node scripts/recordDeploymentArtifact.js');
    console.error('');
    console.error('Or use auto mode (requires dfx):');
    console.error('  node scripts/recordDeploymentArtifact.js --auto');
    console.error('');
    console.error('Make sure you have deployed to mainnet first:');
    console.error('  dfx deploy --network ic');
    process.exit(1);
  }
  
  return { frontendId, backendId };
}

// Generate the deployment links markdown content
function generateMarkdown(frontendId, backendId) {
  const timestamp = new Date().toISOString();
  const publicUrl = `https://${frontendId}.icp0.io`;
  const rawUrl = `https://${frontendId}.raw.icp0.io`;
  const candidUrl = `https://a4gq6-oaaaa-aaaab-qaa4q-cai.raw.icp0.io/?id=${backendId}`;
  
  return `# QA Management App - Deployment Links

This file contains the public website link and canister IDs for the latest IC mainnet deployment.

**Note:** This file is automatically generated/updated by \`frontend/scripts/recordDeploymentArtifact.js\` after successful mainnet deployment.

---

## 🌐 Public Website

**Live Application URL:**
\`\`\`
${publicUrl}
\`\`\`

🔗 **[Open Application](${publicUrl})**

---

## 📦 Canister IDs

**Frontend Canister:**
\`\`\`
${frontendId}
\`\`\`

**Backend Canister:**
\`\`\`
${backendId}
\`\`\`

---

## 📅 Deployment Information

**Last Deployed:** ${new Date(timestamp).toLocaleString('en-US', {
  dateStyle: 'full',
  timeStyle: 'long'
})}

**Network:** Internet Computer Mainnet

---

## 🔗 Alternative URLs

**Raw Frontend URL:**
\`\`\`
${rawUrl}
\`\`\`

**Candid UI (Backend):**
\`\`\`
${candidUrl}
\`\`\`

🔗 **[Open Candid UI](${candidUrl})**

---

## 📝 How to Update

To update this file after a new deployment:

### Automated (Recommended)

\`\`\`bash
node frontend/scripts/publishMainnetAndRecord.js "your-app-name"
\`\`\`

### Manual

\`\`\`bash
# After deploying to mainnet
dfx deploy --network ic

# Update this file
node frontend/scripts/recordDeploymentArtifact.js \\
  --frontend $(dfx canister id frontend --network ic) \\
  --backend $(dfx canister id backend --network ic)
\`\`\`

Or use auto mode:
\`\`\`bash
node frontend/scripts/recordDeploymentArtifact.js --auto
\`\`\`

---

## 📚 Documentation

See \`frontend/DEPLOY_MAINNET.md\` for complete deployment instructions and troubleshooting.
`;
}

// Main execution
function main() {
  console.log('📝 Recording deployment artifact...\n');
  
  const { frontendId, backendId } = getCanisterIds();
  
  console.log('Frontend Canister ID:', frontendId);
  console.log('Backend Canister ID:', backendId);
  console.log('');
  
  const markdown = generateMarkdown(frontendId, backendId);
  const outputPath = path.join(__dirname, '..', 'DEPLOYMENT_LINKS.md');
  
  try {
    fs.writeFileSync(outputPath, markdown, 'utf8');
    console.log('✅ Successfully updated DEPLOYMENT_LINKS.md');
    console.log('');
    console.log('🌐 Public URL:');
    console.log(`   https://${frontendId}.icp0.io`);
    console.log('');
    console.log('📄 View full deployment info:');
    console.log(`   cat ${outputPath}`);
  } catch (error) {
    console.error('❌ Error writing deployment links:', error.message);
    process.exit(1);
  }
}

main();
